BloomBooks/BloomReader-RN

App.tsx, android/app/build.gradle, android/app/src/main/AndroidManifest.xml, android/app/src/main/java/com/bloomreader/AcceptFileHandler.java, android/app/src/main/java/com/bloomreader/GetFromWifiModule.java, android/app/src/main/java/com/bloomreader/GetFromWifiPackage.java, android/app/src/main/java/com/bloomreader/IOUtilities.java, android/app/src/main/java/com/bloomreader/ImportBookModule.java, android/app/src/main/java/com/bloomreader/MainApplication.java, android/app/src/main/java/com/bloomreader/NewBookListenerService.java, android/app/src/main/java/com/bloomreader/SyncServer.java, android/app/src/main/java/com/bloomreader/SyncService.java, app/components/BookList/BookList.tsx, app/components/DrawerMenu/DrawerMenu.tsx, app/components/ReceiveFromWifi/ReceiveFromWifiScreen.tsx, app/components/shared/ProgressSpinner.tsx, app/i18n/locales/en.json, app/i18n/locales/fr.json, app/native_modules/GetFromWifiModule.ts, app/util/ThemeColors.ts, package.json, yarn.lock
There's a lot to this one, but I tried to break it up into logical commits to make it easier to review. So I would review it one commit at a time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader-rn/11)
=> Wifi transfer

android/app/build.gradle, android/app/src/main/AndroidManifest.xml, android/app/src/main/java/org/sil/bloom/reader/AcceptFileHandler.java, android/app/src/main/java/org/sil/bloom/reader/BloomBundleModule.java, android/app/src/main/java/org/sil/bloom/reader/BloomBundlePackage.java, android/app/src/main/java/org/sil/bloom/reader/GetFromWifiModule.java, android/app/src/main/java/org/sil/bloom/reader/GetFromWifiPackage.java, android/app/src/main/java/org/sil/bloom/reader/IOUtilities.java, android/app/src/main/java/org/sil/bloom/reader/ImportBookModule.java, android/app/src/main/java/org/sil/bloom/reader/ImportBooksPackage.java, android/app/src/main/java/org/sil/bloom/reader/MainActivity.java, android/app/src/main/java/org/sil/bloom/reader/MainApplication.java, android/app/src/main/java/org/sil/bloom/reader/NewBookListenerService.java, android/app/src/main/java/org/sil/bloom/reader/ShareApkModule.java, android/app/src/main/java/org/sil/bloom/reader/ShareApkPackage.java, android/app/src/main/java/org/sil/bloom/reader/SyncServer.java, android/app/src/main/java/org/sil/bloom/reader/SyncService.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader-rn/13)
=> Change android package name from com.bloomreader to org.sil.bloom.reader

android/app/src/main/java/org/sil/bloom/reader/MainApplication.java, app/util/BookStorage.ts, app/util/startupTasks.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader-rn/14)
=> Storage fixes

.babelrc, .gitignore, app/models/BookOrShelf.test.ts, app/models/BookOrShelf.ts, app/test/testHelper.ts, app/util/BookStorage.ts, app/util/FileUtil.test.ts, babel.config.js, jest.config.js, package.json, tsconfig.json, yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader-rn/15)
=> Integrate Jest and add some unit tests

.gitignore, ReadMe.md, app/components/BookList/BookList.tsx, integration-tests/intTestHelpers.ts, integration-tests/intTestSetup.ts, integration-tests/readReleaseNotes.ts, integration-tests/testSuite.test.ts, package.json, yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader-rn/18)
=> Use Appium to run integration tests with an emulator.

.gitignore, ReadMe.md, android/app/src/main/java/org/sil/bloom/reader/MainApplication.java, app/components/BookReader/BookReader.tsx, app/components/DrawerMenu/DrawerMenuItem.tsx, app/util/BookStorage.ts, package.json, yarn.lock
Don't merge just yet...we need to publish bloom-player-react on npm and modify this PR by adding it
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader-rn/17)
=> Use real BloomPlayer code

@types/react-native-email/index.d.ts, app/components/BookReader/BookReader.tsx, app/components/DrawerMenu/DrawerMenu.tsx, app/util/BookStorage.ts, app/util/ErrorLog.ts, app/util/FileUtil.ts, app/util/startupTasks.ts, package.json, yarn.lock
Some of the changes in this commit are from Prettier. Do you have Prettier running John, or do we have different settings for it?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader-rn/21)
=> Add Error logging/reporting and fix bug caused by trying to delete openBookDir that didn't exist.

.gitignore, android/app/src/main/assets/bloom-player/webView.htm, app/components/BookReader/BookReader.tsx, copyWebModules.js, package.json, yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader-rn/23)
=> Switch to a modified player that gets the book from a url param

android/app/build.gradle, android/app/src/main/AndroidManifest.xml
Issue: https://issues.bloomlibrary.org/youtrack/issue/BL-7147
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader-rn/27)
=> [BL-7147] Add Product flavors for Alpha, Beta & Production

app/components/BookList/BookListItem.tsx, app/components/BookList/ShelfListItem.tsx, app/i18n/locales/en.json, app/i18n/locales/fr.json, app/models/BookOrShelf.ts, app/util/BookStorage.ts, app/util/ThemeColors.ts, app/util/getFeaturesList.ts, app/util/startupTasks.ts
This issue is in UI-Review; make sure it passes that before merging.
Issue: https://issues.bloomlibrary.org/youtrack/issue/BL-7137
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader-rn/28)
=> [BL-7137] Add speaker icon to audio books in BookList.

android/app/build.gradle, android/app/src/main/java/org/sil/bloom/reader/MainApplication.java, android/settings.gradle, app/components/BookList/BookList.tsx, app/components/ReceiveFromWifi/ReceiveFromWifiScreen.tsx, app/native_modules/ImportBookModule.ts, app/util/BRAnalytics.ts, app/util/BookStorage.ts, app/util/FileUtil.ts, app/util/startupTasks.ts, ios/bloomreader.xcodeproj/project.pbxproj, package.json, yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader-rn/22)
=> Analytics.

android/app/build.gradle
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader-rn/30)
=> Add signing config (BL-7148)

android/build.gradle
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader-rn/32)
=> Get version patch number from TeamCity (BL-7148)

android/app/build.gradle
I will not be surprised if we revert this change...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader-rn/33)
=> Prevent scary warning on Play console regarding not supporting devices (BL-7148)

__mocks__/react-native-fs.js, app/util/BRAnalytics.ts, jest.config.js, package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader-rn/34)
=> Fixes for running Debug Alpha and Unit Tests

android/app/src/main/java/org/sil/bloom/reader/MainApplication.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader-rn/38)
=> Conditionally set up WebView debugging based on API level (BL-7148)

android/app/src/main/AndroidManifest.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader-rn/37)
=> Copy over the intent filters from BloomReader 1.3

.gitignore, app/components/BookReader/BookReader.tsx, app/util/BRAnalytics.ts, copyWebModules.js, package.json, yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader-rn/35)
=> BL-7019 Simple Comprehension Quiz

.vscode/launch.json, app/models/BookOrShelf.test.ts, app/test/testHelper.ts, package.json, yarn.lock
Also add configuration to debug jest in VSCode and bump bloom-player to 0.6.8
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader-rn/41)
=> Fix unit tests

.flowconfig, App.tsx, android/app/BUCK, android/app/build.gradle, android/app/build_defs.bzl, android/app/src/debug/AndroidManifest.xml, android/app/src/main/AndroidManifest.xml, android/app/src/main/java/org/sil/bloom/reader/MainApplication.java, android/app/src/release/AndroidManifest.xml, android/build.gradle, android/gradle/wrapper/gradle-wrapper.properties, android/settings.gradle, app/models/BookCollection.ts, app/util/BRAnalytics.ts, app/util/startupTasks.ts, ios/bloomreader.xcodeproj/project.pbxproj, ios/bloomreader/AppDelegate.m, metro.config.js, package.json, yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader-rn/40)
=> [BL-7154] Upgrade React Native => 0.59.8

app/components/BookReader/BookReader.tsx, app/i18n/i18n.ts, app/i18n/locales/en.json, app/i18n/locales/fr.json, package.json, yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader-rn/44)
=> Send l10n data to bloom-player (BL-7191)

app/components/BookReader/BookReader.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader-rn/45)
=> BL-7211 Support back button message from player

.gitignore, android/app/src/main/assets/bloom-player/webView.htm, copyWebModules.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader-rn/47)
=> Use minified BloomPlayer

package.json, yarn.lock
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader-rn/48)
=> Use latest bloom-player

app/components/BookReader/BookReader.tsx
Note: should not be merged until the corresponding bloom player change is merged AND PUBLISHED to npm
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader-rn/49)
=> BL-7274 Handle requestCapabilities message, report we can go back

android/app/build.gradle, android/app/src/main/java/org/sil/bloom/reader/MainApplication.java, android/settings.gradle, app/components/DrawerMenu/DrawerMenu.tsx, package.json, yarn.lock
And improve the UI of the logo
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader-rn/50)
=> Add version number to the menu drawer (BL-7208)

app/components/BookList/BookListItem.tsx, app/models/BookCollection.ts, app/models/BookOrShelf.ts, app/util/getFeaturesList.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader-rn/54)
=> [BL-7305] Fix usage of meta.json for determining if a book has narration

app/components/BookReader/BookReader.tsx, app/models/BookOrShelf.ts, app/storage/BookStorage.ts, app/util/BRAnalytics.ts, app/util/getFeaturesList.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader-rn/51)
=> BL-7256 Add BookLoaded and PagesRead events (with features)

android/app/src/alpha/play/listings/en-US/title.txt, android/app/src/beta/play/listings/en-US/title.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader-rn/56)
=> Change store listing to BR Alpha/Beta (BL-7232)

.gitignore, app/components/BookReader/BookReader.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader-rn/57)
=> BL-7325 reset counts after reporting pages read on pause

android/app/src/main/java/org/sil/bloom/reader/GetInstallerInfoModule.java, android/app/src/main/java/org/sil/bloom/reader/GetInstallerInfoPackage.java, android/app/src/main/java/org/sil/bloom/reader/MainApplication.java, app/util/BRAnalytics.ts, app/util/startupTasks.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader-rn/55)
=> BL-7257 report source of install using startupTasks

app/components/BookReader/BookReader.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader-rn/58)
=> BL-7317 Don't count page as audio if not actually played

android/app/src/main/java/org/sil/bloom/reader/GetInstallerInfoModule.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader-rn/59)
=> BL-7257 Report source of install even if unknown

app/components/BookReader/BookReader.tsx
Also adds reporting number of pages viewed where video was played, and improves accuracy of reporting pages where audio was played.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader-rn/60)
=> BL-7255 report duration of audio and video played

app/components/BookReader/BookReader.tsx, app/util/BRAnalytics.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomreader-rn/61)
=> BL-7346 Report pages read when finished; add sessionId
